from src.use_cases.find_one_subscriber.find_one_subcriber_controller import FindOneSubscriberController
from src.use_cases.find_one_subscriber.find_one_subcriber_use_case import FindOneSubcriberUseCase

from src.database.repositories.implementations.postgres_subscriber_repository import PostgresSubscriberRepository

postgres_subscriber_repository = PostgresSubscriberRepository()

find_one_subscriber_use_case = FindOneSubcriberUseCase(
    postgres_subscriber_repository)

find_one_subscriber_controller = FindOneSubscriberController(
    find_one_subscriber_use_case
)
